FilmVault/FilmVault/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/movies/', permanent=True)),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FilmVault/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

FilmVault/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='list'),
    #path('review/', views.review_create, name='review'),
    path('<slug:slug>/', views.movie_detail, name='detail'),
]

FilmVault/accounts/models.py
from django.db import models

# Create your models here.

FilmVault/movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    poster = models.ImageField(default='default.png', blank=True)
    director = models.CharField(max_length=100)
    actors = models.CharField(max_length=100)
    year = models.CharField(max_length=4)

    def __str__(self):
        return self.title

FilmVault/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('movies:list')  # Redirect to a home page after signup
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('movies:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})
def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('movies:list')

FilmVault/movies/views.py
from django.shortcuts import render
from .models import Movie
from django.http import HttpResponse

def movie_list(request):
    movies = Movie.objects.all()
    return render(request,'movies/movie_list.html', {'movies': movies})

def movie_detail(request, slug):
    movie = Movie.objects.get(slug=slug)
    return render(request,'movies/movie_details.html',{'movie': movie})

FilmVault/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
</form>
{% endblock %}

FilmVault/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>
{% endblock %}

FilmVault/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Djangonautic blog</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="wrapper">
        <h1>movies</h1>
      {% block content %}
      {% endblock %}
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

FilmVault/templates/movies/movie_details.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>movies</h1>
  <div class="movie">
      <h1> {{ movie.title }} </h1>
      <p> {{ movie.description }} </p>
  </div>
{% endblock %}

FilmVault/templates/movies/movie_list.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="image-grid">
    {% for movie in movies %}
    <a href="{% url 'movies:detail' slug=movie.slug %}"> <img src="{{ movie.poster.url }}"> </a>
    {% endfor %}
</div>
{% endblock %}